name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQubeScan:
    name: SonarQube Scan
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SonarScanner
        run: brew install sonar-scanner

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build Project and Generate Compilation Database
        run: |
          xcodebuild clean build -workspace YourProject.xcworkspace -scheme YourScheme -destination 'platform=iOS Simulator,name=iPhone 15' | xcpretty --report json-compilation-database --output compile_commands.json

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.organization=your-org-name \
            -Dsonar.projectKey=abhinandankhunger_SonarDemo \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
